// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_hiKpCXGWmm8T-7pV_vLszM-C-ruwcXk',
    appId: '1:488019695495:web:0e2ab3527a1c379c7f6522',
    messagingSenderId: '488019695495',
    projectId: 'pillmate-e753c',
    authDomain: 'pillmate-e753c.firebaseapp.com',
    storageBucket: 'pillmate-e753c.firebasestorage.app',
    measurementId: 'G-LTHHDTSN1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjk_dP4hJ9aZIccRnJbtR7S-i3jKvrbFw',
    appId: '1:488019695495:android:8509c69cf2c0f9c87f6522',
    messagingSenderId: '488019695495',
    projectId: 'pillmate-e753c',
    storageBucket: 'pillmate-e753c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs1dsyOW39xUzQJKUiD1NmFQjZAwZ3qzA',
    appId: '1:488019695495:ios:6989c275c68bb2ee7f6522',
    messagingSenderId: '488019695495',
    projectId: 'pillmate-e753c',
    storageBucket: 'pillmate-e753c.firebasestorage.app',
    iosBundleId: 'com.pillmate.pillMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs1dsyOW39xUzQJKUiD1NmFQjZAwZ3qzA',
    appId: '1:488019695495:ios:6989c275c68bb2ee7f6522',
    messagingSenderId: '488019695495',
    projectId: 'pillmate-e753c',
    storageBucket: 'pillmate-e753c.firebasestorage.app',
    iosBundleId: 'com.pillmate.pillMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_hiKpCXGWmm8T-7pV_vLszM-C-ruwcXk',
    appId: '1:488019695495:web:47be78fd4a5915887f6522',
    messagingSenderId: '488019695495',
    projectId: 'pillmate-e753c',
    authDomain: 'pillmate-e753c.firebaseapp.com',
    storageBucket: 'pillmate-e753c.firebasestorage.app',
    measurementId: 'G-7JV0K1WZZT',
  );

}